### ISSUE TITLE
Installation OK mais  impossible de créer une resource 

### ISSUE THREAD

**Issue by luceole** [nunux-keeper/keeper-docker#2]
Après Authentification OK, impossible de créer une resource 

![image](https://user-images.githubusercontent.com/10925916/55384892-2dfd2e80-552c-11e9-878d-358ffa5ee232.png)

**Comment by ncarlier** [comment]
Pouvez-vous montrer le retour des requêtes HTTP. C'est vraisemblablement un pb d'accès à l'api.

**Comment by luceole** [comment]
Effectivement j'ai des erreurs 401
![image](https://user-images.githubusercontent.com/10925916/55716270-d9a7f200-59f6-11e9-8d7b-75be73dd4f6a.png)

**Comment by luceole** [comment]
### Sur mon poste avec url localhost dans .env tout est OK
Sur le serveur de test avec son nom de domaine  Not OK

Pourtant aucune erreur pendant le deploy
root@webkeep:/home/keeper-docker# make deploy
Setup Nunux Keeper...
#########################################
# Nunux Keeper custom configuration
#########################################

# Public base URL
PUBLIC_BASEURL=http://webkeeper.bluehats.fr/


# Host exposed port
PORT=80

# Reverse proxy exposed port
RPROXY_PORT=8080
Creating network "keeperdocker_default" with the default driver
Creating volume "keeperdocker_storage-data" with default driver
Creating volume "keeperdocker_conf-data" with default driver
Creating volume "keeperdocker_www-data" with default driver
Creating keeperdocker_traefik_1 ... 
Creating keeperdocker_keycloak_1 ... 
Creating keeperdocker_traefik_1
Creating keeperdocker_redis_1 ... 
Creating keeperdocker_elasticsearch_1 ... 
Creating keeperdocker_keycloak_1
Creating keeperdocker_mongo_1 ... 
Creating keeperdocker_redis_1
Creating keeperdocker_elasticsearch_1
Creating keeperdocker_elasticsearch_1 ... done
Building Web App...

> keeper@1.0.0 build /usr/src/app
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  209.92 KB  build/static/js/main.d593ddc2.js
  98.84 KB   build/static/css/main.48551f0f.css

The project was built assuming it is hosted at /keeper/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Waiting for keycloak up and ready ("healthy")...
Configuring keycloak...
Starting keeperdocker_keycloak_1 ... done
Logging into http://keycloak:8080/auth as user admin of realm master
Resource not found for url: http://keycloak:8080/auth/admin/realms/keeper-demo
Realm 'keeper-demo' created.
Realm 'keeper-demo' configured.
Client '236d4ec6-837f-4bcd-8ef5-c44f2c429a9e' created.
Created new role with id 'user'
Created new role with id 'admin'
Roles created.
Users created.
Created new group with id 'd89cfa8f-cb76-424c-8a3a-5077fae9915f'
Groups created.
Groups configured.
Admin user affected to the 'Admin' group.
Get realm keys...

Get adapter configuration file...

Keycloak successfully configured.
keeperdocker_redis_1 is up-to-date
keeperdocker_elasticsearch_1 is up-to-date
keeperdocker_keycloak_1 is up-to-date
keeperdocker_traefik_1 is up-to-date
Creating keeperdocker_keeper-web-app_1 ... 
keeperdocker_mongo_1 is up-to-date
Creating keeperdocker_keeper-core-api_1 ... 
Creating keeperdocker_keeper-web-app_1
Creating keeperdocker_keeper-core-api_1 ... done
Creating keeperdocker_keeper-job-worker_1 ... 
Creating keeperdocker_keeper-job-worker_1 ... done
Congrats! Nunux Keeper up and running.

**Comment by luceole** [comment]
Après ré-initialisation complète du serveur de test -  ca fonctionne ! 
Peut être  que le make undeploy n'est pas toujours suffisant et qu'il reste des données dans les volumes docker ?

En tout cas,  je ferme ce signalement.
