### ISSUE TITLE
Cannot add sites to be captured

### ISSUE THREAD

**Issue by danmed** [nunux-keeper/keeper-docker#3]
I've set up a new system for this and the script worked great. All the containers are running.

however when i try to add a page, nothing happens. 

I can't see in the logs for either the keeper-core or the keeper-web containers that anything is going on.

any ideas where i should be looking?

**Comment by danmed** [comment]
I seem to be getting the below errors in the console when trying to create labels or add a new page : 

```
SyntaxError: "JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data" helper.js:26:12
    dispatchAction helper.js:26
    createLabel actions.js:58
```

**Comment by ncarlier** [comment]
Can you check the Network console? Something seems to be wrong with the API. This error means that the API response is not a correct JSON response. Bad API path maybe.

**Comment by danmed** [comment]
> 
> 
> Can you check the Network console? Something seems to be wrong with the API. This error means that the API response is not a correct JSON response. Bad API path maybe.

HI, i just checked and i seem to be getting a 404 POST error potentially..

![image](https://user-images.githubusercontent.com/3878490/63424878-43a1c080-c407-11e9-906b-924b0e3ffc06.png)

**Comment by danmed** [comment]
Here's my traefik screenshot in case that helps at all : 

![image](https://user-images.githubusercontent.com/3878490/63425049-9ed3b300-c407-11e9-9370-91c055a5a279.png)

**Comment by danmed** [comment]
I'm guessing.. that the url is meant to be 

http://<ipaddress>/keeper/api/v2/documents

and not

http://<ipaddress>/api/v2/documents

**Comment by danmed** [comment]
I've redeployed and now traefik has an entry for API and it seems to be working.. seems to be stripping all the css and images out of anything it captures though..

**Comment by ncarlier** [comment]
In your screenshot API frontend and backend was missing.
API URL should be: http://x.x.x.x/api/v2/documents
And Webapp URL should be: http://x.x.x.x/keeper

**Comment by danmed** [comment]
> 
> 
> In your screenshot API frontend and backend was missing.
> API URL should be: http://x.x.x.x/api/v2/documents
> And Webapp URL should be: http://x.x.x.x/keeper

Thanks.. its all working now.. can ijust check though.. there are 2 methods for capturing from a URL..

Extract : Does this literally just get text?
Bookmark : This seems to be get a screenshot of the page?

**Comment by ncarlier** [comment]
Yes.
Extract: get text (keeping the basic formatting) with images
Bokkmark: create a full screenshot of the page
More information here: https://keeper.nunux.org/doc/en/create-doc/
