### ISSUE TITLE
Cannot access hosted keeper-docker

### ISSUE THREAD

**Issue by RyanLiRui** [nunux-keeper/keeper-docker#5]
It doesn't seem to be listening outside of the docker. Please advise on what I should do here. Please see screenshot for reference:
![notlistening](https://user-images.githubusercontent.com/977609/72854584-bdf4aa80-3cef-11ea-8b78-fbc17a856186.jpg)
I have tried using the local network IP in the .env file and that doesn't seem to work either.

**Comment by ncarlier** [comment]
[Traefik container](https://github.com/nunux-keeper/keeper-docker/blob/master/docker-compose.yml#L6) is missing. And you know what? ... I think it's again a version pb!
Traefik 2.0 was released recently and broke the compatibility with the previous one.  Can you try to use `traefik:1.7` instead of `traefik:latest`. 
BTW I think that would be the same for Mongo. Using `latest` for Docker images is definitely not a good idea. `mongo:3` should be bettre than `mongo:latest`.

**Comment by RyanLiRui** [comment]
Thanks ncarlier, 

I applied the changes you told me to apply. Now, I can access the Traefik dashboard. If I go to open the web app, I get a loading spinner and then blank white page. Opening up developer tools shows me this
![web_error](https://user-images.githubusercontent.com/977609/73053912-fd73f000-3ec3-11ea-94a5-70a3cc52259f.PNG)
the full URL of "Failed to load resource" is
http://192.168.0.2/auth/realms/keeper-demo/protocol/openid-connect/login-status-iframe.html

When I try to open the keycloak page, I get a "404 page not found" error.

I wonder if this resource not found for URL message during deployment has some sort of relationship to this problem or not.

![resource_not_found](https://user-images.githubusercontent.com/977609/73054072-6ce9df80-3ec4-11ea-92cd-f101d0a949b2.jpg)

Here is an additional screenshot for your reference of the current situation:
![keeper_not_listening](https://user-images.githubusercontent.com/977609/73054092-7b37fb80-3ec4-11ea-9277-7b2879055eb0.jpg)
By the way, I do realize in the screenshot it shows one of the db servers "starting", but I have tried these sites again once it was up and "healthy", and still no luck.

**Comment by ncarlier** [comment]
I think you have to rebuild the image of keeper-web-app because you change the version of keycloak in the meantime. To be 100% sure, try to remove all built Docker images and try a make deploy again. I did a fresh clone and deploy and everything is working.

**Comment by RyanLiRui** [comment]
I did a "make undeploy" and then a "docker system prune -a", before then doing make deploy again and I'm still running into issues. 

I found that if I try to use the links you provided on the main page there:
![nunux_links](https://user-images.githubusercontent.com/977609/73080162-5a8d9700-3f00-11ea-8d13-06aaab44bfc1.PNG)

I still get the same issues outlined above.

If I use the links provided by the Traefik dashboard which use the docker container's internal IPs, I can get to the keycloak page and use that no problem, and the nunux web app is stuck on a page that is all white except for the words "Loading..." at the top left corner. The error when checking the development tools on chrome in this case is:
![image](https://user-images.githubusercontent.com/977609/73080388-b821e380-3f00-11ea-839d-cfc27c2cf407.png)
the full URL in this case is:
http://192.168.112.3/keeper/static/js/main.2fdef2c4.js

I appreciate your continued support on this. I can go back and delete my repo and try to start everything from scratch, but I would first like to be sure that it's going to be worth it.

**Comment by RyanLiRui** [comment]
ncarlier, I think it's working properly now that I wiped everything out and started from scratch. Thanks for your help.

Unfortunately after finally getting it running, I realized that your service needs to provide a share link for tags (which don't appear on other users' accounts). I was hoping to use this as a means to share important websites on various projects for people within my organization, but I don't think it's going to fit our workflow.

I really appreciate the help, and I applaud you for all the work you did here. If you have any alternative solutions to suggest I'd be happy to explore them. 

Thanks again. I'll mark this issue as closed.

**Comment by ncarlier** [comment]
Hi Ryan,

I'm glad you finally managed to install the stack. Thank you very much for your comments! It's great to have this feedback.
I am unfortunately aware that the sharing part is poorly design! I've never been satisfied about it :/

An alternative solution is maybe to aggregate [RSS feed of your labels](https://keeper.nunux.org/doc/en/share) in a central place.
Bad product placement:  you could use [Feedpushr](https://github.com/ncarlier/feedpushr) and [Readflow](https://readflow.app) ;-)
More seriously, I plan this year to migrate the Nunux Keeper functionalities to Readflow. When the time comes, I will have to study much better this notion of community sharing.
