### ISSUE TITLE
Localhost on public Domain Name

### ISSUE THREAD

**Issue by zoernert** [nunux-keeper/keeper-docker#6]
Hi,

After installing Nunux everything is working fine if I install it with a unchanged ".env" however if I set it to run on a FQDN via https all auth requests get redirected to "localhost:port" . I think I miss the point where to set this. So far I played around with clients settings (Root URL) in keycloak but was not able to find the right point...

**Comment by ncarlier** [comment]
Which HTTP request is redirected?  The first one after authentication? API requests? Or only UI?. Can you open Chrome or Firefox console to see which HTTP request have this issue?

FYI you need to rebuild Docker images if you update `*.env` files.
Regarding the UI you can force Web UI base URL by setting this variable (before Docker build): PUBLIC_URL.
You can also force API URL by setting this variable:  REACT_APP_API_ROOT
If you do that you may have to double check Traefik configuration!

**Comment by zoernert** [comment]
Steps to reproduce (simplified):
```
git clone https://github.com/nunux-keeper/keeper-docker.git

# change .env
cat .env
```
```
#########################################
# Nunux Keeper custom configuration
#########################################

# Public base URL
PUBLIC_BASEURL=https://keep.corrently.cloud

# Host exposed port
PORT=8099

# Reverse proxy exposed port
RPROXY_PORT=8080
```
```
make deploy
```

Open in Browser: https://keep.corrently.cloud/keeper
Expected issue with "invalid redirect URL"

Open SSH Tunnel to open:
http://localhost:8099/auth/admin/master/console/#/realms/keeper-demo/clients/

Valid Redirect URI
```
/keeper/*
https://keep.corrently.cloud/*
```
=> With just this we still have Redirect URI missmatich (which is fine)
I tried with modified Base URL ( https://keep.corrently.cloud/keeper ) on the keeper App Client

**Comment by ncarlier** [comment]
Ho! I just try your link and the "invalid redirect URL" response comes from https://login.nunux.org
It's the official Keycloak instance of Nunux Keeper.
Your file is not correct: https://keep.corrently.cloud/keeper/keycloak.json

it should be something like:

```json
{
  "realm": "nunux-keeper",
  "realm-public-key": "-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY----- ",
  "auth-server-url": "https://keep.corently.cloud/auth",
  "ssl-required": "external",
  "resource": "nunux-keeper-app",
  "public-client": true,
  "enable-cors": true
}
```

This file is generated during the Docker build. You should remove the webapp Docker image and start a new `make deploy` (or `make build-webapp` if you want only to rebuild the webapp)

**Comment by zoernert** [comment]
Ok - got it. So the root cause is within ` dockerfiles/keycloak/setup.sh` where the kecloak.json gets created during initial `make deploy` ? 

Looking at the code (that generates it) it looks fine:
```
$kcadm get clients/$client_id/installation/providers/keycloak-oidc-keycloak-json \
  -r $realm \
  | jq ".[\"auth-server-url\"]=\"$PUBLIC_BASEURL/auth\"" \
  > $output/keycloak.json
```
I just hardcoded `$PUBLIC_BASEURL` and did a `make undeploy; make deploy; make start`to test if this might solve the issue. Now I have again the localhost redirect ... So I am a bit confused.

**Comment by ncarlier** [comment]
The pb is now on Keycloak side.
Yout OpenID Connect endpoint is not correct: https://keep.corrently.cloud/auth/realms/keeper-demo/.well-known/openid-configuration
You should add `PROXY_ADDRESS_FORWARDING=true` to `etc/keycloak.env`.
Make sure that your reverse proxy fill `X-Forwarded-For` and `X-Forwarded-Proto` HTTP headers and preserve the original `Host` HTTP header.

**Comment by zoernert** [comment]
Reverse proxy settings made it finally work.  There is now another instance in the wild :) 

In case I could help you with something - let me know.
